/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.panel;

import GUI.dialog.CTHoaDonDialog;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nhat
 */
public class CTHoaDon extends javax.swing.JPanel {
    private DefaultTableModel model;
    private BUS.CTHoaDonBus bus;
    private int soluongcanxoa=0;
    /**
     * Creates new form CTHoaDonN
     */
    public CTHoaDon() {
        initComponents();
        bus=new BUS.CTHoaDonBus();
        bus.docDs();
        model=(DefaultTableModel) tblcthd.getModel();
        tblcthd.isCellEditable(ERROR, WIDTH);
        loaddata();
    }

    public CTHoaDon(String mahd) {
        initComponents();
        bus=new BUS.CTHoaDonBus();
        txtname.setText("Chi tiết hóa đơn của hóa đơn: "+mahd);
        model=(DefaultTableModel) tblcthd.getModel();
        txttim.setVisible(false);
        btntim.setVisible(false);
        cbtim.setVisible(false);
        btnthem.setVisible(false);
        btnxoa.setVisible(false);
        btnxuat.setVisible(false);
        btnreset.setVisible(false);
        loadchitiet(mahd);
    }
    
        public CTHoaDon(String mahd,int vedu) {
        initComponents();
        bus=new BUS.CTHoaDonBus();
        txtname.setText("Chi tiết hóa đơn của hóa đơn: "+mahd);
        model=(DefaultTableModel) tblcthd.getModel();
        txttim.setVisible(false);
        btntim.setVisible(false);
        cbtim.setVisible(false);
        btnthem.setVisible(false);
        btnxoa.setVisible(false);
        btnxuat.setVisible(false);
        
        if(vedu>0){
            this.soluongcanxoa=vedu;
            btnxoa.setVisible(true);
            txtname.setText("Cần xóa thêm "+vedu+" VÉ");
        }else{
            btnxoa.setVisible(true);
        }
        loadchitiet(mahd);
    }
    
    private void loaddata(){
        model.setRowCount(0);
        DefaultTableModel model=(DefaultTableModel) tblcthd.getModel();
        ArrayList<DTO.CTietHD> ds= BUS.CTHoaDonBus.getDs();
        for(DTO.CTietHD cthd:ds){
            model.addRow(new Object[]{
                cthd.getMaHD(),cthd.getMaKHDi(),String.format("%.0f", cthd.getGiaVe())
            });
        }
       
    }
    
    private void loaddata(ArrayList<DTO.CTietHD> ds){
        model.setRowCount(0);
        String loai =cbtim.getSelectedItem().toString();
        String key=txttim.getText().toString().trim();
        ds= bus.timNangcao(loai, key);
        for(DTO.CTietHD cthd:ds){
            model.addRow(new Object[]{
                cthd.getMaHD(),cthd.getMaKHDi(),cthd.getGiaVe()
            });
        }
    }
    
    private void loadchitiet(String mahd){
        DefaultTableModel model=(DefaultTableModel) tblcthd.getModel();
        this.model.setRowCount(0);
        
        try{
            BUS.CTHoaDonBus bus=new BUS.CTHoaDonBus();
            ArrayList<DTO.CTietHD> ds=bus.getDstheoma(mahd);
            if(ds!=null){
                for(DTO.CTietHD cthd:ds){
                    model.addRow(new Object[]{
                        cthd.getMaHD(),cthd.getMaKHDi(),cthd.getGiaVe()
                    });
                }
            }
        }catch(Exception e){
                    e.printStackTrace();
                    JOptionPane.showMessageDialog(this, "Loi");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtname = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        cbtim = new javax.swing.JComboBox<>();
        txttim = new javax.swing.JTextField();
        btntim = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblcthd = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btnthem = new javax.swing.JButton();
        btnxoa = new javax.swing.JButton();
        btnreset = new javax.swing.JButton();
        btnxuat = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        txtname.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtname.setText("Quản lý Chi tiết hóa đơn");
        jPanel1.add(txtname, java.awt.BorderLayout.CENTER);

        cbtim.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mã hóa đơn", "Mã khách hàng" }));
        jPanel2.add(cbtim);

        txttim.setColumns(20);
        jPanel2.add(txttim);

        btntim.setText("Tìm");
        btntim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntimActionPerformed(evt);
            }
        });
        jPanel2.add(btntim);

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_END);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        tblcthd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã hóa đơn", "Mã khách hàng", "Giá vé"
            }
        ));
        jScrollPane1.setViewportView(tblcthd);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        btnthem.setText("Thêm");
        btnthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemActionPerformed(evt);
            }
        });
        jPanel3.add(btnthem);

        btnxoa.setText("Xóa");
        btnxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaActionPerformed(evt);
            }
        });
        jPanel3.add(btnxoa);

        btnreset.setText("Làm mới");
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });
        jPanel3.add(btnreset);

        btnxuat.setText("Xuất excel");
        btnxuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxuatActionPerformed(evt);
            }
        });
        jPanel3.add(btnxuat);

        add(jPanel3, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void btnthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemActionPerformed
        // TODO add your handling code here:
        CTHoaDonDialog cthd=new CTHoaDonDialog();
        cthd.setModal(true);
        cthd.setVisible(true);
        loaddata();
    }//GEN-LAST:event_btnthemActionPerformed

    private void btnxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaActionPerformed
        // TODO add your handling code here:
        int row=tblcthd.getSelectedRow();

        if(row==-1){
            JOptionPane.showMessageDialog(this, "Vui lòng chọn chi tiết cần xóa");
            return;
        }
        
        String mahd =model.getValueAt(row, 0).toString();
        String makh =model.getValueAt(row, 1).toString();
        
        if(JOptionPane.showConfirmDialog(this, "Xóa vé này?","Xác nhận",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){
            if(bus.xoaCtietHd(mahd,makh)){
                model.removeRow(row);
                JOptionPane.showMessageDialog(this, "Xóa thành công");

                if(soluongcanxoa>0){
                    soluongcanxoa--;
                    if(soluongcanxoa>0){
                        txtname.setText("Cần xóa thêm "+soluongcanxoa+" VÉ");
                        
                    }else{
                        txtname.setText("Đã xóa đủ");
                    }
                }
            }
        }
    }//GEN-LAST:event_btnxoaActionPerformed

    private void btntimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntimActionPerformed
        // TODO add your handling code here:
              String tim =txttim.getText().toString().trim();
      
        String loai= cbtim.getSelectedItem().toString();
        
        if(tim.isEmpty()){
            model.setRowCount(0);
            return;
        }else {
        loaddata(bus.timNangcao(loai, tim));
        }
        
    }//GEN-LAST:event_btntimActionPerformed

    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
        // TODO add your handling code here:
        loaddata();
    }//GEN-LAST:event_btnresetActionPerformed

    private void btnxuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxuatActionPerformed
        // TODO add your handling code here:
        Helper.ExcelHelper.xuatExcel(tblcthd, this, "Danh sách chi tiết hóa đơn");
    }//GEN-LAST:event_btnxuatActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnreset;
    private javax.swing.JButton btnthem;
    private javax.swing.JButton btntim;
    private javax.swing.JButton btnxoa;
    private javax.swing.JButton btnxuat;
    private javax.swing.JComboBox<String> cbtim;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblcthd;
    private javax.swing.JLabel txtname;
    private javax.swing.JTextField txttim;
    // End of variables declaration//GEN-END:variables
}
