/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.panel;
import javax.swing.table.DefaultTableModel;
import DTO.CTrinhKMDTO;
import DTO.KMTourDTO;

import java.util.ArrayList;
import java.util.Comparator;

import javax.swing.*;
import GUI.dialog.CTrinhKMDialog;
/**
 *
 * @author CZ01
 */
public class CTrinhKMPanel extends javax.swing.JPanel {

    private BUS.CTrinhKMBUS bus;
    private DefaultTableModel model;
    /**
     * Creates new form CTrinhKMPanel
     */
    public CTrinhKMPanel() {
        initComponents();
        tblKM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblKMMouseClicked(evt);
            }
        });
        bus=new BUS.CTrinhKMBUS();
        model = (DefaultTableModel) tblKM.getModel();
        tblKM.setDefaultEditor(Object.class, null);
        loadData();
    }

    private void loadData() {
    model.setRowCount(0); // Xóa dữ liệu cũ
    ArrayList<CTrinhKMDTO> list = new ArrayList<>(bus.getDsCTrinhKM());
    list.sort(Comparator.comparing(CTrinhKMDTO::getMaKM));
        for (CTrinhKMDTO km : list) {
        model.addRow(new Object[]{
            km.getMaKM(),
            km.getTenKM(),
            km.getNgayBD(),
            km.getNgayKT(),
            km.getHinhThucKM() ? "KMHD" : "KMTour",
            km.getChietKhau(),
            km.getGhiChu()
        });
    }
}

    private void loadData(String loai, String keyword) {
        model.setRowCount(0); // Xóa dữ liệu cũ
        bus.searchCTrinhKM(loai, keyword).forEach(km -> {
            model.addRow(new Object[]{
                km.getMaKM(),
                km.getTenKM(),
                km.getNgayBD(),
                km.getNgayKT(),
                km.getHinhThucKM() ? "KMHD" : "KMTour",
                km.getChietKhau(),
                km.getGhiChu()
            });
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        cbbKM = new javax.swing.JComboBox<>();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKM = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnDel = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnLoad = new javax.swing.JButton();
        btnXuat = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(623, 300));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setAlignmentX(0.0F);
        jPanel1.setAlignmentY(0.0F);
        jPanel1.setPreferredSize(new java.awt.Dimension(623, 50));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("QUẢN LÝ KHUYẾN MÃI");
        jPanel1.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 100, 5, 100));
        jPanel2.setAlignmentX(0.0F);
        jPanel2.setAlignmentY(0.0F);
        jPanel2.setMinimumSize(new java.awt.Dimension(230, 35));
        jPanel2.setPreferredSize(new java.awt.Dimension(100, 45));

        cbbKM.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cbbKM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả", "KMHD", "KMTour" }));
        cbbKM.setToolTipText("");
        cbbKM.setMinimumSize(new java.awt.Dimension(91, 20));
        cbbKM.setName(""); // NOI18N
        cbbKM.setPreferredSize(new java.awt.Dimension(81, 30));
        cbbKM.addActionListener(this::cbbKMActionPerformed);
        jPanel2.add(cbbKM);

        txtSearch.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSearch.setToolTipText("");
        txtSearch.setAlignmentX(2.0F);
        txtSearch.setAlignmentY(20.0F);
        txtSearch.setMargin(new java.awt.Insets(5, 10, 5, 10));
        txtSearch.setMinimumSize(new java.awt.Dimension(40, 22));
        txtSearch.setPreferredSize(new java.awt.Dimension(250, 28));
        txtSearch.addActionListener(this::txtSearchActionPerformed);
        jPanel2.add(txtSearch);

        btnSearch.setText("Tìm");
        btnSearch.addActionListener(this::btnSearchActionPerformed);
        btnSearch.setPreferredSize(new java.awt.Dimension(75, 30));
        jPanel2.add(btnSearch);

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_END);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        tblKM.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã KM", "Tên KM", "Ngày BD", "Ngày KT", "Hình thức", "Chiết Khấu(%)", "Ghi chú"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblKM);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 5));

        btnAdd.setText("Thêm");
        btnAdd.addActionListener(this::btnAddActionPerformed);
        jPanel3.add(btnAdd);

        btnDel.setText("Xóa");
        btnDel.addActionListener(this::btnDelActionPerformed);
        jPanel3.add(btnDel);

        btnEdit.setText("Chỉnh sửa");
        btnEdit.addActionListener(this::btnEditActionPerformed);
        jPanel3.add(btnEdit);

        btnLoad.setText("Load");
        btnLoad.addActionListener(this::btnLoadActionPerformed);
        jPanel3.add(btnLoad);

        btnXuat.setText("Xuất Excel");
        btnXuat.addActionListener(this::btnXuatActionPerformed);
        jPanel3.add(btnXuat);

        add(jPanel3, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents
    
    private void tblKMMouseClicked(java.awt.event.MouseEvent evt) {

        int row = tblKM.rowAtPoint(evt.getPoint());

        if (row >= 0) {

            btnEdit.setEnabled(true);
            btnDel.setEnabled(true);

            if (evt.getClickCount() == 2 && !evt.isConsumed()) {

                evt.consume();

                String[] option = {/*"Xem chi tiết",*/ "Chỉnh sửa", "Hủy"};

                int choice = JOptionPane.showOptionDialog(
                        this,
                        "Bạn muốn làm gì với chương trình khuyến mãi này?",
                        "Lựa chọn",
                        JOptionPane.DEFAULT_OPTION,
                        JOptionPane.INFORMATION_MESSAGE,
                        null,
                        option,
                        option[0]
                );

                if (choice == 0) {
                    String maKM = tblKM.getValueAt(row, 0).toString();
                    CTrinhKMDTO ct = bus.getFullCTrinhKM(maKM);
                    if (ct != null) {
                        CTrinhKMDialog dialog = new CTrinhKMDialog(bus, ct);
                        dialog.setModal(true);
                        dialog.setVisible(true);
                        loadData();
                    } else {
                        JOptionPane.showMessageDialog(this, "Không tìm thấy chi tiết chương trình khuyến mãi.");
                    }
                }
            }
        }
    }          
                
    
    private void cbbKMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbKMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbKMActionPerformed
    
    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        String tim = txtSearch.getText().toString().trim();
        String loai =cbbKM.getSelectedItem().toString().trim();

        if(tim.isEmpty()){
            JOptionPane.showMessageDialog(this, "Vui lòng nhập thông tin cần tìm");
            loadData();
        }else {
            loadData(loai, tim);
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        GUI.dialog.CTrinhKMDialog dialog=new GUI.dialog.CTrinhKMDialog(bus);
        dialog.setModal(true);
        dialog.setVisible(true);
        loadData();
    }//GEN-LAST:event_btnAddActionPerformed

   private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {
    int row = tblKM.getSelectedRow();
    if (row >= 0) {
        String maKM = tblKM.getValueAt(row, 0).toString();
        CTrinhKMDTO ct = bus.getFullCTrinhKM(maKM);  // Lấy chi tiết
        if (ct != null) {
            CTrinhKMDialog dialog = new CTrinhKMDialog(bus, ct);
            dialog.setModal(true);
            dialog.setVisible(true);
            loadData();
        } else {
            JOptionPane.showMessageDialog(this, "Không tìm thấy chi tiết chương trình khuyến mãi.");
        }
    } else {
        JOptionPane.showMessageDialog(this, "Vui lòng chọn một chương trình khuyến mãi để chỉnh sửa.");
    }
}          

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
        // TODO add your handling code here:
        try{
            int row = tblKM.getSelectedRow();
            
            if (row >= 0) {
                int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xóa chương trình khuyến mãi này?", "Xác nhận", JOptionPane.YES_NO_OPTION);
                if (confirm == JOptionPane.YES_OPTION) {
                    String maKM = model.getValueAt(row, 0).toString();
                    if(bus.xoaCTrinhKM(maKM)) {
                        DefaultTableModel model = (DefaultTableModel) tblKM.getModel();
                        model.removeRow(row);
                        loadData();
                        JOptionPane.showMessageDialog(this, "Xóa chương trình khuyến mãi thành công.");
                    } else {
                        JOptionPane.showMessageDialog(this, "Xóa chương trình khuyến mãi thất bại.");
                    }
                }
            } else {
                JOptionPane.showMessageDialog(this, "Vui lòng chọn một chương trình khuyến mãi để xóa.");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Có lỗi xảy ra khi xóa chương trình khuyến mãi.");
        }
    }//GEN-LAST:event_btnDelActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void btnLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadActionPerformed
        // TODO add your handling code here:
        loadData();
    }//GEN-LAST:event_btnLoadActionPerformed

    private void btnXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatActionPerformed
        // TODO add your handling code here:
        Helper.ExcelHelper.xuatExcel(tblKM, this, "Danh sách khuyến mãi");
    }//GEN-LAST:event_btnXuatActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnLoad;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnXuat;
    private javax.swing.JComboBox<String> cbbKM;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblKM;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}


