/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.Panel;

import BUS.NhanVienBUS;
import DAO.NhanVienDAO;
import DTO.NhanVien;
import GUI.Dialog.NhanVienDialog;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Admin
 */
public class NhanVienPanel extends javax.swing.JPanel {

    /**
     * Creates new form QLNhanVien
     */
    NhanVienDAO ds = new NhanVienDAO();
    NhanVienBUS nvBUS = new NhanVienBUS();
    NhanVienDialog NVdialog;
    public NhanVienPanel() {
        nvBUS = new NhanVienBUS();
        initComponents();
        txtSearch.getDocument().addDocumentListener(new DocumentListener() {

        private void search() {
            String keyword = txtSearch.getText().trim();
            List<NhanVien> list = nvBUS.timNhanVien(getColumnName(jComboBox1.getSelectedItem().toString()), keyword);
            loadNhanVienToTable(list);
        }

        @Override
        public void insertUpdate(DocumentEvent e) {
            search();
        }

        @Override
        public void removeUpdate(DocumentEvent e) {
            search();
        }

        @Override
        public void changedUpdate(DocumentEvent e) {
            search();
        }
    });
        loadNhanVienToTable(ds.layDanhSachNV());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        txtSearch = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Quản lí nhân viên");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel1, java.awt.BorderLayout.CENTER);

        jLabel2.setText("Tìm kiếm");
        jPanel2.add(jLabel2);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mã nhân viên", "Họ", "Tên", "Chức vụ", "Ngày sinh", "Số điện thoại", "Địa chỉ" }));
        jComboBox1.addActionListener(this::jComboBox1ActionPerformed);
        jPanel2.add(jComboBox1);

        txtSearch.setPreferredSize(new java.awt.Dimension(360, 22));
        txtSearch.addActionListener(this::txtSearchActionPerformed);
        jPanel2.add(txtSearch);

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_END);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã nhân viên", "Họ", "Tên", "Chức vụ", "Ngày sinh", "Số điện thoại", "Địa chỉ"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jButton1.setText("Thêm");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        jPanel3.add(jButton1);

        jButton2.setText("Xóa");
        jButton2.setEnabled(false);
        jButton2.addActionListener(this::jButton2ActionPerformed);
        jPanel3.add(jButton2);

        jButton3.setText("Sửa");
        jButton3.setEnabled(false);
        jButton3.addActionListener(this::jButton3ActionPerformed);
        jPanel3.add(jButton3);

        jButton4.setText("Làm mới");
        jPanel3.add(jButton4);

        add(jPanel3, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {

        NhanVienDialog dialog = new NhanVienDialog(
                null,
                true,
                ds,
                NhanVienDialog.Mode.ADD,
                null
        );

        dialog.setVisible(true);

        loadNhanVienToTable(ds.layDanhSachNV());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int i = jTable1.getSelectedRow();
        int result = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xóa nhân viên này?", "Xác nhận xóa", JOptionPane.YES_NO_OPTION);
        if (result == JOptionPane.YES_OPTION && i >= 0) {
            String maNV = jTable1.getValueAt(i, 0).toString();
            NhanVienBUS nvBUS = new NhanVienBUS();
            nvBUS.xoaNhanVien(maNV);
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.removeRow(i);
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int i = jTable1.getSelectedRow();

        if (i >= 0) {
            String maNV = jTable1.getValueAt(i, 0).toString();
            NhanVien nv = nvBUS.timNhanVienTheoMa(maNV);
            System.err.println(nv.getMaNV());
            NhanVienDialog dialog = new NhanVienDialog(
                null, true, ds,
                NhanVienDialog.Mode.EDIT,
                nv);

            dialog.setVisible(true);
            loadNhanVienToTable(ds.layDanhSachNV());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt){
        jButton2.setEnabled(true);
        jButton3.setEnabled(true);
    }

    private void searchNhanVien() {
    String keyword = txtSearch.getText().trim();
    String selected = jComboBox1.getSelectedItem().toString();

    List<NhanVien> list;

    if (keyword.isEmpty()) {
        loadNhanVienToTable(ds.layDanhSachNV());
        return;
    }

    if (selected.equals("Ngày sinh")) {
        try {
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
            LocalDate date = LocalDate.parse(keyword, formatter);

            list = nvBUS.timNhanVienTheoNgaySinh(date);
        } catch (Exception e) {
            list = new ArrayList<>();
        }
    } else {
        String column = getColumnName(selected);
        list = nvBUS.timNhanVien(column, keyword);
    }

    loadNhanVienToTable(list);
}

    private String getColumnName(String selected) {

    switch (selected) {
        case "Mã nhân viên":
            return "maNV";
        case "Họ":
            return "ho";
        case "Tên":
            return "ten";
        case "Chức vụ":
            return "chucVu";
        case "Số điện thoại":
            return "sdt";
        case "Địa chỉ":
            return "diaChi";
        default:
            return "maNV"; 
    }
}

    private void loadNhanVienToTable(List<NhanVien> list) {

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0); // Xóa dữ liệu cũ trong bảng
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");

        for(NhanVien nv : list){
            Date date = java.sql.Date.valueOf(nv.getNgaySinh());
            String ngaySinhStr = "";
            if(date!=null){
                LocalDate localDate = ((java.sql.Date) date).toLocalDate();
                ngaySinhStr = localDate.format(formatter);
            }

            model.addRow(new Object[]{
                nv.getMaNV(),
                nv.getHo(),
                nv.getTen(),
                nv.getChucVu(),
                ngaySinhStr,
                nv.getSdt(),
                nv.getDiaChi()
            });
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
