/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.example.gui.panel;
import org.example.gui.dialog.DiaDiemDialog;
import org.example.dao.DiaDiemDAO;
import org.example.bus.DiaDiemBUS;
import org.example.bus.HoaDonBUS;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.example.dto.*;
/**
 *
 * @author Nhat
 */
public class DiaDiemPanel extends javax.swing.JPanel {
    private DefaultTableModel model;
    private org.example.bus.DiaDiemBUS bus;
    /**
     * Creates new form DiaDiemN
     */
    public DiaDiemPanel() {
        initComponents();
        bus=new org.example.bus.DiaDiemBUS();
        model = (DefaultTableModel) tbldd.getModel();
        loadData();
    }

    private void loadData(){
        model.setRowCount(0);
        
        ArrayList<org.example.dto.DiaDiemDTO> ds = DiaDiemBUS.getDs();
     if(ds==null) return;
     for(org.example.dto.DiaDiemDTO dd: ds){
         model.addRow(new Object[]{
             dd.getTenDiaDiem(),org.example.helper.DateHelper.toString(dd.getNgayThucHien()),String.format("%.0f", dd.getTongChi())});
     }
    }

    
    private void loadData(ArrayList<org.example.dto.DiaDiemDTO> ds,String ma){
        model.setRowCount(0);
        
     ds = bus.timdd(ma);
     if(ds==null) return;
     for(org.example.dto.DiaDiemDTO dd: ds){
         model.addRow(new Object[]{
             dd.getTenDiaDiem(),org.example.helper.DateHelper.toString(dd.getNgayThucHien()),dd.getTongChi()});
     }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txttendd = new javax.swing.JTextField();
        btntim = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbldd = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btnthem = new javax.swing.JButton();
        btnxoa = new javax.swing.JButton();
        btnsua = new javax.swing.JButton();
        btnreset = new javax.swing.JButton();
        btnxuat = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Quản lý địa điểm");
        jPanel1.add(jLabel1, java.awt.BorderLayout.CENTER);

        jLabel2.setText("Tên địa điểm");
        jPanel2.add(jLabel2);

        txttendd.setColumns(20);
        jPanel2.add(txttendd);

        btntim.setText("Tìm");
        btntim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntimActionPerformed(evt);
            }
        });
        jPanel2.add(btntim);

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_END);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        tbldd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên địa điểm", "Ngày thực hiện", "Tổng chi"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbldd.setPreferredSize(new java.awt.Dimension(450, 450));
        tbldd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblddMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbldd);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        btnthem.setText("Thêm");
        btnthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemActionPerformed(evt);
            }
        });
        jPanel3.add(btnthem);

        btnxoa.setText("Xóa");
        btnxoa.setEnabled(false);
        btnxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaActionPerformed(evt);
            }
        });
        jPanel3.add(btnxoa);

        btnsua.setText("Sửa");
        btnsua.setEnabled(false);
        btnsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuaActionPerformed(evt);
            }
        });
        jPanel3.add(btnsua);

        btnreset.setText("Làm mới");
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });
        jPanel3.add(btnreset);

        btnxuat.setText("Xuất excel");
        btnxuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxuatActionPerformed(evt);
            }
        });
        jPanel3.add(btnxuat);

        add(jPanel3, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void tblddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblddMouseClicked
        // TODO add your handling code here:
        int row = tbldd.getSelectedRow();
        if(row!=-1){
            btnsua.setEnabled(true);
            btnxoa.setEnabled(true);
            if(evt.getClickCount()==2){
                int cf=JOptionPane.showConfirmDialog(this, "Bạn có muốn xuất Excel dòng này không?");
                
                if(cf==JOptionPane.YES_OPTION){
                    org.example.helper.ExcelHelper.xuatExcel1Dong(tbldd, row, jPanel1, "Địa điểm: "+bus.timdd(tbldd.getValueAt(row, 0).toString().trim()));
                }else{
                    return;
                }
            }
        }
    }//GEN-LAST:event_tblddMouseClicked

    private void btnxuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxuatActionPerformed
        // TODO add your handling code here:
        org.example.helper.ExcelHelper.xuatExcel(tbldd, this, "Danh sach hoa don");
    }//GEN-LAST:event_btnxuatActionPerformed

    private void btnthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemActionPerformed
        // TODO add your handling code here:
        DiaDiemDialog ddd=new DiaDiemDialog();
        ddd.setModal(true);
        ddd.setVisible(true);
        loadData();
    }//GEN-LAST:event_btnthemActionPerformed

    private void btnxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaActionPerformed
        // TODO add your handling code here:
        int row=tbldd.getSelectedRow();

        if(row==-1){
            JOptionPane.showMessageDialog(this, "Vui lòng chọn địa điểm cần xóa");
            return;
        }
        String tendd =model.getValueAt(row, 0).toString();
        org.example.dto.DiaDiemDTO dd=bus.timDiaDiem(tendd); if(dd==null){
            JOptionPane.showMessageDialog(this, "Lỗi không tìm thấy");
            return;
            }
        if(JOptionPane.showConfirmDialog(this, "Xóa địa điểm?","Xác nhận",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){
            if(bus.xoaDiaDiem(dd)){
                JOptionPane.showMessageDialog(this, "Xóa thành công");
                loadData();
            }else{
                JOptionPane.showMessageDialog(this, "Xóa thất bại");
            }
    }//GEN-LAST:event_btnxoaActionPerformed
    }
    
    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
        // TODO add your handling code here:
        loadData();
    }//GEN-LAST:event_btnresetActionPerformed

    private void btntimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntimActionPerformed
        // TODO add your handling code here:

        loadData(bus.timdd(txttendd.getText().trim()), txttendd.getText().trim());
    }//GEN-LAST:event_btntimActionPerformed

    private void btnsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuaActionPerformed
        // TODO add your handling code here:
        int row=tbldd.getSelectedRow();
        if(row!=-1){
            String ten=tbldd.getValueAt(row, 0).toString().trim();
            DiaDiemDTO dd =bus.timDiaDiem(ten);
        DiaDiemDialog ddd=new DiaDiemDialog(dd);
        ddd.setModal(true);
        ddd.setVisible(true);
        }
    }//GEN-LAST:event_btnsuaActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnreset;
    private javax.swing.JButton btnsua;
    private javax.swing.JButton btnthem;
    private javax.swing.JButton btntim;
    private javax.swing.JButton btnxoa;
    private javax.swing.JButton btnxuat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbldd;
    private javax.swing.JTextField txttendd;
    // End of variables declaration//GEN-END:variables
}
