/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.panel;

import BUS.HoaDonBus;
import java.awt.FlowLayout;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nhat
 */
public class HoaDon extends javax.swing.JPanel {
    private BUS.HoaDonBus bus;
    private DefaultTableModel model;
    /**
     * Creates new form HoaDonNew
     */
    public HoaDon() {
        initComponents();
        bus=new BUS.HoaDonBus();
        model=(DefaultTableModel) tblhoadon.getModel();
        JPanel southPanel = new JPanel(new FlowLayout(FlowLayout.CENTER, 15, 10));
        loadData();;
    }

    private void loadData(){
     model.setRowCount(0);
     bus.docDs();
     ArrayList<DTO.HoaDon> ds = HoaDonBus.getDs();
     if(ds==null) return;
     for(DTO.HoaDon hd: ds){
         model.addRow(new Object[]{
             hd.getMaHD(),hd.getMaKHTour(),hd.getMaKHDat(),hd.getMaNV(),Helper.DateHelper.toString(hd.getNgay()),hd.getSoluong(),String.format("%.0f",hd.getTongTien())
         });
     }
    }
    
    private void loadData(String loai,String key){
     model.setRowCount(0);
     bus.docDs();
     ArrayList<DTO.HoaDon> ds =bus.timNangcao(loai, key);
     if(ds==null) return;
     for(DTO.HoaDon hd: ds){
         model.addRow(new Object[]{
             hd.getMaHD(),hd.getMaKHTour(),hd.getMaKHDat(),hd.getMaNV(),Helper.DateHelper.toString(hd.getNgay()),hd.getSoluong(),hd.getTongTien()
         });
     }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        cbtim = new javax.swing.JComboBox<>();
        txttim = new javax.swing.JTextField();
        btntim = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblhoadon = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btnthem = new javax.swing.JButton();
        btnxoa = new javax.swing.JButton();
        btnsua = new javax.swing.JButton();
        btnreset = new javax.swing.JButton();
        btnxuat = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Quản lý hóa đơn");
        jPanel1.add(jLabel2, java.awt.BorderLayout.CENTER);

        cbtim.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mã hóa đơn", "Mã kế hoạch tour", "Mã khách hàng đặt", "Mã nhân viên" }));
        jPanel2.add(cbtim);

        txttim.setColumns(20);
        txttim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttimActionPerformed(evt);
            }
        });
        jPanel2.add(txttim);

        btntim.setText("Tìm");
        btntim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntimActionPerformed(evt);
            }
        });
        jPanel2.add(btntim);

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_END);

        add(jPanel1, java.awt.BorderLayout.NORTH);

        tblhoadon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã hóa đơn", "Mã kế hoạch tour", "Mã khách hàng đặt", "Mã nhân viên", "Ngày", "Số lượng", "Tổng tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblhoadon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblhoadonMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblhoadon);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        btnthem.setText("Thêm");
        btnthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemActionPerformed(evt);
            }
        });
        jPanel3.add(btnthem);

        btnxoa.setText("Xóa");
        btnxoa.setEnabled(false);
        btnxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaActionPerformed(evt);
            }
        });
        jPanel3.add(btnxoa);

        btnsua.setText("Chỉnh sửa");
        btnsua.setEnabled(false);
        btnsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuaActionPerformed(evt);
            }
        });
        jPanel3.add(btnsua);

        btnreset.setText("Làm mới");
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });
        jPanel3.add(btnreset);

        btnxuat.setText("Xuất excel");
        btnxuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxuatActionPerformed(evt);
            }
        });
        jPanel3.add(btnxuat);

        add(jPanel3, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void tblhoadonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblhoadonMouseClicked
        // TODO add your handling code here:
        int row =tblhoadon.getSelectedRow();
        if(row>=0){
            btnsua.setEnabled(true);
            btnxoa.setEnabled(true);
            
            if(evt.getClickCount()==2){
                String ma=tblhoadon.getValueAt(row, 0).toString();
                
                String[] option={"Chỉnh sửa","Chi tiết hóa đơn","Hủy"};
                
                int choice=JOptionPane.showOptionDialog(this, "Vui lòng chọn lựa chọn", "Tùy chọn", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, option, option[1]);
                
                if(choice==0){
                    DTO.HoaDon hd=new DTO.HoaDon(tblhoadon.getValueAt(row, 0).toString(), tblhoadon.getValueAt(row, 1).toString(), tblhoadon.getValueAt(row, 2).toString(), tblhoadon.getValueAt(row, 3).toString(), LocalDate.parse(tblhoadon.getValueAt(row, 4).toString()),Integer.parseInt(tblhoadon.getValueAt(row, 5).toString()),Float.parseFloat(tblhoadon.getValueAt(row, 6).toString()));
                    GUI.dialog.HoaDonDialog hdd =new GUI.dialog.HoaDonDialog(hd);
                    hdd.setModal(true);
                    hdd.setVisible(true);
                    loadData();
                }else if(choice==1){
                    GUI.panel.CTHoaDon cthd=new GUI.panel.CTHoaDon(ma);
                    
                    int result=JOptionPane.showConfirmDialog(null, cthd,"Chi tiết hóa đơn",JOptionPane.OK_CANCEL_OPTION,JOptionPane.PLAIN_MESSAGE);
                    loadData();
                    if(result==JOptionPane.OK_OPTION){
                        return;
                    }
                }else if(choice==2){
                    return;
                }
            }            
        }
    }//GEN-LAST:event_tblhoadonMouseClicked

    private void btnthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemActionPerformed
        // TODO add your handling code here:
        GUI.dialog.HoaDonDialog hdd=new GUI.dialog.HoaDonDialog();
        hdd.setModal(true);
        hdd.setVisible(true);
        loadData();
    }//GEN-LAST:event_btnthemActionPerformed

    private void btnxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaActionPerformed
        // TODO add your handling code here:
        try{
            int row =tblhoadon.getSelectedRow();

            if(row==-1){
                JOptionPane.showMessageDialog(this, "Vui lòng chọn hóa đơn cần xóa");
                return;
            }
            int cf =JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa không?","Xác nhận",JOptionPane.YES_NO_OPTION);
            if(cf==JOptionPane.YES_OPTION){
                String ma = tblhoadon.getValueAt(row, 0).toString();
                DTO.HoaDon hd=bus.timHd(ma);

                if(bus.xoaHoaDon(ma)){
                    DefaultTableModel model=(DefaultTableModel) tblhoadon.getModel();

                    model.removeRow(row);
                    loadData();
                    JOptionPane.showMessageDialog(this, "Xóa thành công");
                }

            }
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnxoaActionPerformed

    private void btnxuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxuatActionPerformed
        // TODO add your handling code here:
        Helper.ExcelHelper.xuatExcel(tblhoadon, this, "Danh sách hóa đơn");
    }//GEN-LAST:event_btnxuatActionPerformed

    private void btntimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntimActionPerformed
        // TODO add your handling code here:
        String tim = txttim.getText().toString().trim();
        String loai =cbtim.getSelectedItem().toString().trim();

        if(tim.isEmpty()){
            JOptionPane.showMessageDialog(this, "Vui lòng nhập thông tin cần tìm");
            loadData();
        }else {
            loadData(loai, tim);
        }

    }//GEN-LAST:event_btntimActionPerformed

    private void txttimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttimActionPerformed

    private void btnsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuaActionPerformed
        // TODO add your handling code here:
        
        int row =tblhoadon.getSelectedRow();
        
        if(row==-1){
            JOptionPane.showMessageDialog(this, "Vui lòng chọn dòng cần sửa");
            return;
        }
        String ma =tblhoadon.getValueAt(row, 0).toString().trim();
        DTO.HoaDon hd=bus.timHd(ma);
        if(hd!=null){
            GUI.dialog.HoaDonDialog hdd=new GUI.dialog.HoaDonDialog(hd);
            hdd.setModal(true);
            hdd.setVisible(true);
            loadData();
        }else{
            JOptionPane.showMessageDialog(this, "Không tìm thấy dữ liệu hóa đơn");
        }
    }//GEN-LAST:event_btnsuaActionPerformed

    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
        // TODO add your handling code here:
        loadData();
    }//GEN-LAST:event_btnresetActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnreset;
    private javax.swing.JButton btnsua;
    private javax.swing.JButton btnthem;
    private javax.swing.JButton btntim;
    private javax.swing.JButton btnxoa;
    private javax.swing.JButton btnxuat;
    private javax.swing.JComboBox<String> cbtim;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblhoadon;
    private javax.swing.JTextField txttim;
    // End of variables declaration//GEN-END:variables
}
