/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package org.example.gui.dialog;

import java.awt.event.KeyAdapter;
import org.example.dto.CTietHDDTO;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.InputVerifier;
import javax.swing.JComboBox;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import org.example.bus.*;
import org.example.dto.*;
/**
 *
 * @author Nhat
 */
public class CTHoaDonDialog extends javax.swing.JDialog {
    private org.example.bus.CTHoaDonBUS bus;
    private HoaDonBUS hdbus;
    private KhachHangBUS khbus;
    /**
     * Creates new form CTHoaDonDialog
     */
    public CTHoaDonDialog() {
        initComponents();
        loadCbox();
        this.setTitle("Chi tiết hóa đơn");
        this.bus=new org.example.bus.CTHoaDonBUS();
        this.setLocationRelativeTo(null);
    }
        public void loadCbox(){
        this.hdbus=new HoaDonBUS();
        this.khbus =new KhachHangBUS();
        ArrayList<KhachHang> dskh =KhachHangBUS.dsKH;
        ArrayList<HoaDonDTO> dshd =HoaDonBUS.ds;
        List<String> dsMa = new ArrayList<>();
        
        for(HoaDonDTO hd: dshd){
            dsMa.add(hd.getMaHD());
        }
        setupAutoComplete(cbmahd, dsMa);
        dsMa=new ArrayList<>();
        for(KhachHang kh:dskh){
            dsMa.add(kh.getMaKH());
        }
        setupAutoComplete(cbmakh, dsMa);
    }
    
    public void setupAutoComplete(JComboBox<String> cbx, List<String> data) {
    cbx.setEditable(true);
    cbx.setModel(new DefaultComboBoxModel<>(data.toArray(new String[0])));
    JTextField txt = (JTextField) cbx.getEditor().getEditorComponent();
    
    txt.addKeyListener(new KeyAdapter() {
        @Override
        public void keyReleased(KeyEvent e) {
            int k = e.getKeyCode();
            if (k == 38 || k == 40 || k == 10) return; 
            
            SwingUtilities.invokeLater(() -> {
                String input = txt.getText();
                
                String[] filtered = data.stream()
                        .filter(s -> s.toLowerCase().contains(input.toLowerCase()))
                        .toArray(String[]::new);
                        
                cbx.setModel(new DefaultComboBoxModel<>(filtered));
                txt.setText(input); 
                cbx.setPopupVisible(filtered.length > 0);
            });
        }
    });
}
    
    public void resetField(){
        cbmahd.setSelectedItem("");
        cbmakh.setSelectedItem("");
        txtgiave.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtgiave = new javax.swing.JTextField();
        btnluu = new javax.swing.JButton();
        btnreset = new javax.swing.JButton();
        cbmahd = new javax.swing.JComboBox<>();
        cbmakh = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Mã hóa đơn");

        jLabel2.setText("Mã khách hàng đi");

        jLabel3.setText("Giá vé");

        txtgiave.setToolTipText("");
        txtgiave.setEnabled(false);
        txtgiave.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtgiaveFocusLost(evt);
            }
        });
        txtgiave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtgiaveActionPerformed(evt);
            }
        });

        btnluu.setText("Lưu");
        btnluu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnluuActionPerformed(evt);
            }
        });

        btnreset.setText("Làm mới");
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });

        cbmakh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbmakhActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(btnluu, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(btnreset))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbmakh, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbmahd, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtgiave, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE))))
                .addContainerGap(11, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(132, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(94, Short.MAX_VALUE)
                .addComponent(cbmahd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbmakh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(txtgiave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnluu)
                    .addComponent(btnreset))
                .addGap(47, 47, 47))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(94, 94, 94)
                    .addComponent(jLabel1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jLabel2)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel3)
                    .addContainerGap(101, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtgiaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtgiaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtgiaveActionPerformed

    private void btnluuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnluuActionPerformed
        // TODO add your handling code here:
        try{
            String ma=cbmahd.getSelectedItem().toString().trim();
            String makh=cbmakh.getSelectedItem().toString().trim();
            if(ma.isEmpty()){
                JOptionPane.showMessageDialog(this, "Lỗi chưa nhập mã hóa đơn");
                return;
            }
           org.example.dto.CTietHDDTO cthd=new org.example.dto.CTietHDDTO(ma, makh,Float.parseFloat(txtgiave.getText()));
        org.example.dto.CTietHDDTO kt=bus.timCt(ma,cbmahd.getSelectedItem().toString().trim());
        
        if(kt!=null){
            if(bus.suaCtiethd(cthd)){
                resetField();
                JOptionPane.showMessageDialog(this, "Cập nhật chi tiết hóa đơn thành công");
                this.dispose();
            }
            else{
                JOptionPane.showMessageDialog(this, "Cập nhật thất bại");
                return;
            }
        }else{
            ArrayList<org.example.dto.CTietHDDTO> ds=new ArrayList<>();
            if(bus.themCTietHd(cthd)){
                resetField();
                JOptionPane.showMessageDialog(this, "Thêm thành công");
                this.dispose();
        }else{
                JOptionPane.showMessageDialog(this, "Thêm thất bại");
                return;
            }
        }   
        }catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi");
        }
    }//GEN-LAST:event_btnluuActionPerformed

    private void txtgiaveFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtgiaveFocusLost
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtgiaveFocusLost

    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
        // TODO add your handling code here:
        resetField();
    }//GEN-LAST:event_btnresetActionPerformed

    private void cbmakhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbmakhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbmakhActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CTHoaDonDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CTHoaDonDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CTHoaDonDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CTHoaDonDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CTHoaDonDialog dialog = new CTHoaDonDialog();
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnluu;
    private javax.swing.JButton btnreset;
    private javax.swing.JComboBox<String> cbmahd;
    private javax.swing.JComboBox<String> cbmakh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtgiave;
    // End of variables declaration//GEN-END:variables
}
