/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nhat
 */
public class CTHoaDon extends javax.swing.JPanel {
    private DefaultTableModel model;
    private BUS.CTHoaDonBus bus;
    /**
     * Creates new form CTHoaDonn
     */
    public CTHoaDon() {
        initComponents();
        bus=new BUS.CTHoaDonBus();
        model=(DefaultTableModel) tblcthd.getModel();
        loaddata();
    }
    
    public CTHoaDon(String mahd) {
        initComponents();
        bus=new BUS.CTHoaDonBus();
        model=(DefaultTableModel) tblcthd.getModel();
        loadchitiet(mahd);
    }
    
    private void loaddata(){
        model.setRowCount(0);
        
        ArrayList<DTO.CTietHD> ds= BUS.CTHoaDonBus.getDs();
        for(DTO.CTietHD cthd:ds){
            model.addRow(new Object[]{
                cthd.getMaHD(),cthd.getMaKHDi(),cthd.getGiaVe()
            });
        }
    }
    
    private void loaddata(ArrayList<DTO.CTietHD> ds){
        model.setRowCount(0);
        String loai =cbtim.getSelectedItem().toString();
        String key=txttim.getText().toString().trim();
        ds= bus.timNangcao(loai, key);
        for(DTO.CTietHD cthd:ds){
            model.addRow(new Object[]{
                cthd.getMaHD(),cthd.getMaKHDi(),cthd.getGiaVe()
            });
        }
    }
    
    private void loadchitiet(String mahd){
        DefaultTableModel model=(DefaultTableModel) tblcthd.getModel();
        this.model.setRowCount(0);
        
        try{
            BUS.CTHoaDonBus bus=new BUS.CTHoaDonBus();
            ArrayList<DTO.CTietHD> ds=bus.getDstheoma(mahd);
            if(ds!=null){
                for(DTO.CTietHD cthd:ds){
                    model.addRow(new Object[]{
                        cthd.getMaHD(),cthd.getMaKHDi(),cthd.getGiaVe()
                    });
                }
            }
        }catch(Exception e){
                    e.printStackTrace();
                    JOptionPane.showMessageDialog(this, "Loi");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblcthd = new javax.swing.JTable();
        btnthem = new javax.swing.JButton();
        btnxoa = new javax.swing.JButton();
        btnxuat = new javax.swing.JButton();
        btntim = new javax.swing.JButton();
        cbtim = new javax.swing.JComboBox<>();
        txttim = new javax.swing.JTextField();

        tblcthd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã hóa đơn", "Mã khách hàng", "Giá vé"
            }
        ));
        tblcthd.setPreferredSize(new java.awt.Dimension(450, 80));
        jScrollPane1.setViewportView(tblcthd);

        btnthem.setText("Thêm");
        btnthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemActionPerformed(evt);
            }
        });

        btnxoa.setText("Xóa");
        btnxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaActionPerformed(evt);
            }
        });

        btnxuat.setText("Xuất excel");

        btntim.setText("Tìm");
        btntim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntimActionPerformed(evt);
            }
        });

        cbtim.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mã hóa đơn", "Mã khách hàng" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnthem)
                        .addGap(27, 27, 27)
                        .addComponent(btnxoa)
                        .addGap(40, 40, 40)
                        .addComponent(btnxuat))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbtim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(txttim, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(btntim)))
                .addContainerGap(232, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btntim)
                    .addComponent(cbtim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnxoa)
                    .addComponent(btnthem)
                    .addComponent(btnxuat))
                .addGap(0, 209, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaActionPerformed
        // TODO add your handling code here:
        int row=tblcthd.getSelectedRow();
        
        if(row==-1){
            JOptionPane.showMessageDialog(this, "Vui lòng chọn địa điểm cần xóa");
            return;
        }
        DTO.CTietHD ct=bus.timCt(model.getValueAt(row, 0).toString(),model.getValueAt(row, 1).toString());
        if(bus.xoaCtietHd(ct)){
            DefaultTableModel model=(DefaultTableModel) tblcthd.getModel();
            model.removeRow(row);
        }
    }//GEN-LAST:event_btnxoaActionPerformed

    private void btnthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemActionPerformed
        // TODO add your handling code here:
        CTHoaDonDialog cthd=new CTHoaDonDialog();
        cthd.setModal(true);
        cthd.setVisible(true);
        loaddata();
    }//GEN-LAST:event_btnthemActionPerformed

    private void btntimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntimActionPerformed
        // TODO add your handling code here:
        String tim =txttim.getText().toString().trim();
      
        String loai= cbtim.getSelectedItem().toString();
        
        if(tim.isEmpty()){
            model.setRowCount(0);
            return;
        }else {
        loaddata(bus.timNangcao(loai, tim));
        }
    }//GEN-LAST:event_btntimActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnthem;
    private javax.swing.JButton btntim;
    private javax.swing.JButton btnxoa;
    private javax.swing.JButton btnxuat;
    private javax.swing.JComboBox<String> cbtim;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblcthd;
    private javax.swing.JTextField txttim;
    // End of variables declaration//GEN-END:variables
}
