/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import BUS.HoaDonBus;
import DAO.DsHoaDon;
import javax.swing.table.DefaultTableModel;
import java.util.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Nhat
 */
public class HoaDon extends javax.swing.JPanel {
    private BUS.HoaDonBus bus;
    private DefaultTableModel model;
    /**
     * Creates new form HoaDon
     */
    public HoaDon() {
        initComponents();
        bus=new BUS.HoaDonBus();
        model=(DefaultTableModel) tblhoadon.getModel();
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void loadData(){
     model.setRowCount(0);

     ArrayList<DTO.HoaDon> ds = HoaDonBus.getDs();
     if(ds==null) return;
     for(DTO.HoaDon hd: ds){
         model.addRow(new Object[]{
             hd.getMaHD(),hd.getMaKHTour(),hd.getMaKHDat(),hd.getMaNV(),hd.getSoluong(),hd.getTongTien()
         });
     }
    }
    
    private void loadData(String loai,String key){
     model.setRowCount(0);
     ArrayList<DTO.HoaDon> ds =bus.timNangcao(loai, key);
     if(ds==null) return;
     for(DTO.HoaDon hd: ds){
         model.addRow(new Object[]{
             hd.getMaHD(),hd.getMaKHTour(),hd.getMaKHDat(),hd.getMaNV(),hd.getSoluong(),hd.getTongTien()
         });
     }
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnthem = new javax.swing.JButton();
        btnxoa = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblhoadon = new javax.swing.JTable();
        txttim = new javax.swing.JTextField();
        btntim = new javax.swing.JButton();
        btnxuat = new javax.swing.JButton();
        cbtim = new javax.swing.JComboBox<>();

        btnthem.setText("Thêm");
        btnthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemActionPerformed(evt);
            }
        });

        btnxoa.setText("Xóa");
        btnxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaActionPerformed(evt);
            }
        });

        tblhoadon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã hóa đơn", "Mã kế hoạch tour", "Mã khách hàng đặt", "Mã nhân viên", "Số lượng", "Tổng tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblhoadon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblhoadonMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblhoadon);

        btntim.setText("Tìm");
        btntim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntimActionPerformed(evt);
            }
        });

        btnxuat.setText("Xuất excel");
        btnxuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxuatActionPerformed(evt);
            }
        });

        cbtim.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mã hóa đơn", "Mã kế hoạch tour", "Mã khách hàng đặt", "Mã nhân viên" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbtim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(txttim, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(btntim))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 732, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnthem)
                        .addGap(52, 52, 52)
                        .addComponent(btnxoa)
                        .addGap(54, 54, 54)
                        .addComponent(btnxuat, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(247, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btntim)
                    .addComponent(txttim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbtim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnthem)
                    .addComponent(btnxoa)
                    .addComponent(btnxuat))
                .addContainerGap(444, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemActionPerformed
        // TODO add your handling code here:
        GUI.HoaDonDialog hdd=new GUI.HoaDonDialog();
        hdd.setModal(true);
        hdd.setVisible(true);
        loadData();
    }//GEN-LAST:event_btnthemActionPerformed

    private void btnxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaActionPerformed
        // TODO add your handling code here:
        try{
            int row =tblhoadon.getSelectedRow();
            
            if(row==-1){
                JOptionPane.showMessageDialog(this, "Vui lòng chọn hóa đơn cần xóa");
            }
            int cf =JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa không?");
            if(cf==JOptionPane.YES_OPTION){
                String ma = tblhoadon.getValueAt(row, 0).toString();
                DTO.HoaDon hd=bus.timHd(ma);
                
                if(bus.xoaHoaDon(ma)){
                    DefaultTableModel model=(DefaultTableModel) tblhoadon.getModel();
                    
                    model.removeRow(row);
                    JOptionPane.showMessageDialog(this, "Xóa thành công");
                }
                
            }
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnxoaActionPerformed

    private void tblhoadonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblhoadonMouseClicked
        // TODO add your handling code here:
        int row =tblhoadon.getSelectedRow();
        if(row>=0){
            String mahd =tblhoadon.getValueAt(row, 0).toString();
            GUI.CTHoaDon cthd=new GUI.CTHoaDon(mahd);
            int result=JOptionPane.showConfirmDialog(null, cthd,"Chi tiết hóa đơn",JOptionPane.OK_CANCEL_OPTION,JOptionPane.PLAIN_MESSAGE);
            if(result==JOptionPane.OK_OPTION){
                return;
            }
        }
        DTO.HoaDon hd=new DTO.HoaDon(tblhoadon.getValueAt(row, 0).toString(), tblhoadon.getValueAt(row, 1).toString(), tblhoadon.getValueAt(row, 2).toString(), tblhoadon.getValueAt(row, 3).toString(), Integer.parseInt(tblhoadon.getValueAt(row, 4).toString()),Float.parseFloat(tblhoadon.getValueAt(row, 5).toString()));
    }//GEN-LAST:event_tblhoadonMouseClicked

    private void btntimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntimActionPerformed
        // TODO add your handling code here:
        String tim = txttim.getText().toString().trim();
        String loai =cbtim.getSelectedItem().toString().trim();
        
        if(tim.isEmpty()){
            JOptionPane.showMessageDialog(this, "Vui lòng nhập thông tin cần tìm");
            loadData();
        }else {
            loadData(loai, tim);
        }
        
    }//GEN-LAST:event_btntimActionPerformed

    private void btnxuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxuatActionPerformed
        // TODO add your handling code here:
        Helper.ExcelHelper.xuatExcel(tblhoadon, this, "Danh sach hoa don");
    }//GEN-LAST:event_btnxuatActionPerformed
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnthem;
    private javax.swing.JButton btntim;
    private javax.swing.JButton btnxoa;
    private javax.swing.JButton btnxuat;
    private javax.swing.JComboBox<String> cbtim;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblhoadon;
    private javax.swing.JTextField txttim;
    // End of variables declaration//GEN-END:variables
}
